apiVersion: v1
kind: Service
metadata:
 name: cloud-service-resigistory-service
 labels: 
  app: cloud-service-registory
spec:
 selector:
  app: cloud-service-registory
 ports:
  - protocol: http
    port: 80
    targetPort: 8163