apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: cloud-service-registory
  name: cloud-service-registory-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: cloud-service-registory
  template: 
    metadata: 
      labels: 
        app: cloud-service-registory
      name: cloud-service-registory-deployment
      spec: 
        containers: 
          - image: "njsingh/purple-cloud-service-registory:latest"
            name: cloud-service-registory
            ports: 
              - containerPort: 80
        imagePullSecret: 
          name: regsecret