apiVersion: v1
kind: Pod
metadata:
 name: cloud-service-registory
 labels:
  app: cloud-service-registory
 namespace: default
spec:
 containers:
  - name: service-registory
    image: njsingh/purple-cloud-service-registory:v1
    ports: 
     - containerPort: 8163
 imagePullSecrets:
  - name: regsecret